-----------------------------------
-- Daily Quest : Saltlik
-- Kill a certain NM
-----------------------------------
require("modules/module_utils")
require("scripts/globals/zone")
require("scripts/zones/Lower_Jeuno/Zone")
local ID = require("scripts/zones/Lower_Jeuno/IDs")
-----------------------------------
local m = Module:new("daily_quest_saltlik")

m:addOverride("xi.zones.Lower_Jeuno.Zone.onInitialize", function(zone)

    super(zone)

    local questLocations =
    {
        -- [index] | Zone Name | NM Name
        [1] = {"West Ronfaure",             {"Amanita","Jaggedy-Eared Jack","Fungus Beetle"}},
        [2] = {"East Ronfaure",             {"Bigmouth Billy","Swamfisk","Rambukk"}},
        [3] = {"South Gustaberg",           {"Tococo","Leaping Lizzy","Carnero"}},
        [4] = {"North Gustaberg",           {"Stinging Sophie","Maighdean Uaine","Bedrock Barry"}},
        [5] = {"West Sarutabaruta",         {"Numbing Norman","Nunyenunc","Tom Tit Tat"}},
        [6] = {"East Sarutabaruta",         {"Duke Decapod","Spiny Spipi","Sharp-Eared Ropipi"}},
        [7] = {"La Theine Plateau",         {"Nihniknoovi","Slumbering Samwell","Tumbling Truffle","Lumbering Lambert","Bloodtear Baldurf"}},
        [8] = {"Konschtat Highlands",       {"Ghillie Dhu","Highlander Lizard","Rampaging Ram","Steelfleece Baldarich","Stray Mary"}},
        [9] = {"Tahrongi Canyon",           {"Yara Ma Yha Who","Habrok","Serpopard Ishtar","Herbage Hunter"}},
        [10] = {"Valkurm Dunes",            {"Metal Shears","Golden Bat","Valkurm Emperor","Hippomaritimus"}},
        [11] = {"Jugner Forest",            {"Panzer Percival","Fraelissa","Meteormauler Zhagtegg","Sappy Sycamore","Supplespine Mujwuj"}},
        [12] = {"Batallia Downs",           {"Tottering Toby","Weeping Willow","Eyegouger","Ahtu","Lumber Jack","Prankster Maverix","Skirling Liger"}},
        [13] = {"Pashhow Marshlands",       {"Bloodpool Vorax","Bo'Who Warmonger","Jolly Green","Toxic Tamlyn","Ni'Zho Bladebender"}},
        [14] = {"Rolanberry Fields",        {"Black Triple Stars","Drooling Daisy","Silk Caterpillar","Ravenous Crawler","Eldritch Edge"}},
        [15] = {"Sauromugue Champaign",     {"Deadly Dodo","Bashe","Thunderclaw Thuban","Blighting Brand"}},
        [16] = {"Beaucedine Glacier",       {"Calcabrina","Gargantua","Humbaba","Kirata","Nue"}},
        [17] = {"Xarcabard",                {"Barbaric Weapon","Duke Focalor","Ereshkigal","Shadow Eye","Timeworn Warrior"}},
        [18] = {"Cape Teriggan",            {"Frostmane","Kreutzet","Killer Jonny","Tegmine","Zmey Gorynych"}},
        [19] = {"Eastern Altepa Desert",    {"Centurio XII-I","Donnergugi","Dune Widow","Nandi"}},
        [20] = {"Western Altepa Desert",    {"Cactuar Cantautor","Calchas","Celphie","Dahu","Picolaton"}},
        [21] = {"Meriphataud Mountains",    {"Daggerclaw Dracos","Patripatan","Chonchon","Waraxe Beak","Naa Zeku the Unwaiting"}},
        [22] = {"Buburimu Peninsula",       {"Backoo","Buburimboo","Helldiver","Wake Warder Wanda"}},
        [23] = {"The Sanctuary of Zi'Tah",  {"Bastet","Elusive Edwin","Huwasi","Keeper of Halidom","Noble Mold"}},
        [24] = {"Ro'Maeve",                 {"Nightmare Vase","Martinet","Nargun","Rogue Receptacle"}},
        [25] = {"Yuhtunga Jungle",          {"Bayawak","Koropokkur","Meww the Turtlerider","Mischievous Micholas","Pyuu the Spatemaker","Rose Garden","Voluptuous Vilma"}},
        [26] = {"Yhoator Jungle",           {"Acolnahuacatl","Bisque-heeled Sunberry","Bright-handed Kunberry","Edacious Opo-opo","Hoar-knuckled Rimberry","Powderer Penny","Woodland Sage"}},
        [27] = {"Qufim Island",             {"Dosetsu Tree","Slippery Sucker","Trickster Kinetix","Atkorkamuy","Qoofim"}},
        [28] = {"Temple of Uggalepih",      {"Bonze Marberry","Death from Above","Flauros","Habetrot","Manipulator","Sacrificial Goblet","Sozu Terberry","Tonberry Kinq"}},
        [29] = {"Valley of Sorrows",        {"Adamantoise"}},
        [30] = {"Bibiki Bay",               {"Intulo","Splacknuck","Shankha","Serra"}},
        [31] = {"Carpenter's Landing",      {"Hercules Beetle","Mycophile","Orctrap","Tempest Tigon"}},
        [32] = {"Uleguerand Range",         {"Black Coney","Bonnacon","Father Frost","Geush Urvan","Magnotaur","Mountain Worm","Skvader","Snow Maiden","White Coney"}},
        [33] = {"Attohwa Chasm",            {"Ambusher Antlion","Citipati","Sargas","Sekhmet"}},
        [34] = {"Oldton Movalpolos",        {"Bugbear Strongman","Goblin Wolfman","Bugbear Muscleman"}},
        [35] = {"Newton Movalpolos",        {"Bugbear Matman","Goblin Collector","Sword Sorcerer Solisoq","Swashstox Beadblinker"}},
        [36] = {"Wajaom Woodlands",         {"Gharial","Jaded Jody","Zoraal Ja's Pkuucha"}},
        [37] = {"Bhaflau Thickets",         {"Emergent Elm","Harvestman","Mahishasura","Nis Puk"}},
        [38] = {"Arrapago Reef",            {"Bloody Bones","Euryale","Lamie No.7","Lamie No.8","Lamie No.9","Lamia No.19","Merrow No.5"}},
        [39] = {"Mount Zhayolm",            {"Chary Apkallu","Energetic Eruca","Garfurlar the Rabid","Garharlor the Unruly","Garhorlur the Brutal","Fahrafahr the Bloodied","Ignamoth"}},
        [40] = {"Halvung",                  {"Copper Borer","Dorgerwor the Astute","Farlarder the Shrewd","Flammeri","Kirlirger the Abhorrent","Mythril Mouth Monamaq"}},
        [41] = {"Mamook",                   {"Darting Kachaal Ja","Devout Radol Ja","Dragonscaled Bugaal Ja","Firedance Magmaal Ja","Hundredfaced Hapool Ja","Venomfang","Zizzy Zillah"}},
        [42] = {"Aydeewa Subterrane",       {"Bluestreak Gyugyuroon","Crystal Eater","Lizardtrap"}},
        [43] = {"Alzadaal Undersea Ruins",  {"Boompadu","Cookieduster Lipiroon","Oupire"}},
        [44] = {"Caedarva Mire",            {"Aynu-kaysey","Peallaidh","Vidhuwa the Wrathborn","Zikko"}},
        [45] = {"Yughott Grotto",           {"Ashmaker Gotblut"}},
        [46] = {"Fort Ghelsba",             {"Chariotbuster Byakzak","Hundredscar Hajwaj","Orcish Panzer","Kegpaunch Doshgnosh"}},
        [47] = {"Palborough Mines",         {"Bu'Ghi Howlblade","No'Mho Crimsonarmor","Zi'Ghi Boneeater","Be'Hya Hundredwall","Qu'Vho Deathhurler"}},
        [48] = {"Giddeus",                  {"Eyy Mon the Ironbreaker","Hoo Mjuu the Torrent","Juu Duzu the Whirlwind","Quu Xijo the Illusory","Vuu Puqu the Beguiler","Zhuu Buxu the Silent"}},
        [49] = {"Beadeaux",                 {"Bi'Gho Headtaker","Da'Dha Hundredmask","De'Vyu Headhunter","Ga'Bhu Unvanquished","Ge'Dha Evileye","Go'Bhu Gascon","Zo'Khu Blackcloud"}},
        [50] = {"Davoi",                    {"Blubbery Bulge","Dirtyhanded Gochakzuk","Hawkeyed Dnatbat","Poisonhand Gnadgad","Steelbiter Gudrud","Tigerbane Bakdak"}},
        [51] = {"Monastic Cavern",          {"Orcish Hexspinner","Orcish Overlord","Orcish Warlord","Overlord Bakgodek"}},
        [52] = {"Castle Oztroja",           {"Moo Ouzi the Swiftblade","Mee Deggi the Punisher","Quu Domi the Gallant","Saa Doyi the Fervid","Yaa Haqa the Profane","Yagudo High Priest","Yagudo Templar","Lii Jixa the Somnolist"}},
        [53] = {"The Boyahda Tree",         {"Ancient Goobbue","Aquarius","Ellyllon","Leshonki","Unut","Voluptuous Vivian"}},
        [54] = {"Lower Delkfutt's Tower",   {"Epialtes","Eurymedon","Hippolytos","Tyrant"}},
        [55] = {"Middle Delkfutt's Tower",  {"Eurytos","Ogygos","Ophion","Polybotes","Rhoikos","Rhoitos"}},
        [56] = {"Upper Delkfutt's Tower",   {"Alkyoneus","Enkelados","Ixtab","Mimas","Pallas","Porphyrion","Autarch"}},
        [57] = {"Den of Rancor",            {"Bistre-hearted Malberry","Carmine-tailed Janberry","Celeste-eyed Tozberry","Friar Rush","Ogama","Sozu Bliberry","Tawny-fingered Mugberry","Tonberry Decapitator","Tonberry Pontifex","Tonberry Tracker"}},
        [58] = {"Castle Zvahl Baileys",     {"Duke Haborym","Grand Duke Batym","Likho","Marquis Allocen","Marquis Amon","Marquis Naberius","Marquis Sabnock"}},
        [59] = {"Castle Zvahl Keep",        {"Baron Vapula","Baronet Romwe","Count Bifrons","Viscount Morax"}},
        [60] = {"Ranguemont Pass",          {"Mucoid Mass","Taisaijin","Gloom Eye","Hyakume"}},
        [61] = {"Bostaunieux Oubliette",    {"Arioch","Bloodsucker","Drexerion the Condemned","Manes","Phanduron the Condemned","Sewer Syrup","Shii"}},
        [62] = {"Toraimarai Canal",         {"Canal Moocher","Brazen Bones","Konjac"}},
        [63] = {"Korroloka Tunnel",         {"Cargo Crab Colin","Dame Blanche","Falcatus Aranei","Morion Worm","Thoon"}},
        [64] = {"Kuftal Tunnel",            {"Amemet","Arachne","Bloodthirster Madkix","Cancer","Guivre","Pelican","Phantom Worm","Sabotender Mariachi","Yowie"}},
        [65] = {"The Eldieme Necropolis",   {"Cwn Cyrff","Skull of Envy","Skull of Gluttony","Skull of Greed","Skull of Lust","Skull of Pride","Skull of Sloth","Skull of Wrath"}},
        [66] = {"Sea Serpent Grotto",       {"Abyss Sahagin","Coral Sahagin","Denn the Orcavoiced","Fyuu the Seabellow","Masan","Mouu the Waverider","Namtar","Novv the Whitehearted","Ocean Sahagin","Pahh the Gullcaller","Qull the Shellbuster","Sea Hog","Seww the Squidlimbed","Voll the Sharkfinned","Worr the Clawfisted","Wuur the Sandcomber","Yarr the Pearleyed","Zuug the Shoreleaper"}},
        [67] = {"Dangruf Wadi",             {"Chocoboleech","Geyser Lizard","Teporingo"}},
        [68] = {"Inner Horutoto Ruins",     {"Maltha","Nocuous Weapon","Slendlix Spindlethumb"}},
        [69] = {"Outer Horutoto Ruins",     {"Bomb King","Doppelganger Dio","Doppelganger Gog","Legalox Heftyhind","Ah Puch","Desmodont"}},
        [70] = {"Ordelle's Caves",          {"Aroma Leech","Bombast","Donggu","Morbolger","Agar Agar"}},
        [71] = {"Gusgen Mines",             {"Aroma Fly","Asphyxiated Amsel","Burned Bergmann","Crushed Krause","Juggler Hecatomb","Pulverized Pfeffer","Smothered Schmidt","Wounded Wurfel"}},
        [72] = {"Crawler's Nest",           {"Aqrabuamelu","Awd Goggie","Demonic Tiphia","Drone Crawler","Dynast Beetle","Guardian Crawler","Matron Crawler","Queen Crawler"}},
        [73] = {"Maze of Shakhrami",        {"Lesath","Aroma Crawler","Gloombound Lurker","Trembler Tabitha"}},
        [74] = {"Garlaige Citadel",         {"Frogamander","Hazmat","Old Two-Wings","Hovering Hotpot"}},
        [75] = {"Fei'Yin",                  {"Capricious Cassie","Eastern Shadow","Goliath","Jenglot","Mind Hoarder","Northern Shadow","Sluagh","Southern Shadow","Western Shadow"}},
        [76] = {"Ifrit's Cauldron",         {"Ash Dragon","Bomb Queen","Foreseer Oramix","Lindwurm","Tarasque","Tyrannic Tunnok","Vouivre"}},
        [77] = {"Quicksand Caves",          {"Antican Consul","Antican Legatus","Antican Magister","Antican Praefectus","Antican Praetor","Antican Proconsul","Antican Tribunus","Centurio X-I","Diamond Daig","Hastatus XI-XII","Nussknacker","Proconsul XII","Sabotender Bailarin","Sabotender Bailarina","Sagittarius X-XIII","Triarius X-XV","Tribunus VII-I"}},
        [78] = {"Gustav Tunnel",            {"Amikiri","Baobhan Sith","Bune","Goblinsavior Heronox","Taxim","Ungur","Wyvernpoacher Drachlox"}},
        [79] = {"Labyrinth of Onzozo",      {"Hellion","Mysticmaker Profblix","Narasimha","Ose","Peg Powler","Soulstealer Skullnix"}},
        [80] = {"Dynamis - Bastok",         {"Aa'Nyu Dismantler","Be'Ebo Tortoisedriver","Gu'Nhi Noondozer","Gi'Pha Manameister","Ko'Dho Cannonball","Ze'Vho Fallsplitter","Gu'Dha Effigy","Zo'Pha Forgesoul","Ra'Gho Darkfount","Va'Zhe Pummelsong","Bu'Bho Truesteel"}},
        [81] = {"Dynamis - San d'Oria",     {"Reapertongue Gadgquok","Voidstreaker Butchnotch","Wyrmgnasher Bjakdek","Battlechoir Gitchfotch","Soulsender Fugbrag","Bladeburner Rokgevok","Steelshank Kratzvatz","Bloodfist Voshgrosh","Spellspear Djokvukk"}},
        [82] = {"Dynamis - Windurst",       {"Haa Pevi the Stentorian","Loo Hepe the Eyepiercer","Wuu Qoho the Razorclaw","Xoo Kaza the Solemn","Xuu Bhoqa the Enigma","Fuu Tzapo the Blessed","Naa Yixo the Stillrage","Tee Zaksa the Ceaseless","Maa Febi the Steadfast"}},
        [83] = {"Dynamis - Jeuno",          {"Bandrix Rockjaw","Buffrix Eargone","Cloktix Longnail","Elixmix Hooknose","Gabblox Magpietongue","Hermitrix Toothrot","Humnox Drumbelly","Lurklox Dhalmelneck","Morgmox Moldnoggin","Sparkspox Sweatbrow","Ticktox Beadyeyes","Trailblix Goatmug","Tufflix Loglimbs","Wyrmwix Snakespecs","Karashix Swollenskull","Kikklix Longlegs","Rutrix Hamgams","Snypestix Eaglebeak","Mortilox Wartpaws","Jabkix Pigeonpecs","Smeltix Thickhide","Wasabix Callusdigit","Anvilix Sootwrists","Blazox Boneybod","Bootrix Jaggedelbow","Distilix Stickytoes","Eremix Snottynostril","Jabbrox Grannyguise","Mobpix Mucousmouth","Prowlox Barrelbelly","Scruffix Shaggychest","Slystix Megapeepers","Tymexox Ninefingers","Quicktrix Hexhands","Feralox Honeylips","Scourquix Scaleskin","Wilywox Tenderpalm"}},
        [84] = {"Dynamis - Beaucedine",     {"Ascetox Ratgums","Bordox Kittyback","Brewnix Bittypupils","Draklix Scalecrust","Droprix Granitepalms","Gibberox Pimplebeak","Moltenox Stubthumbs","Morblox Chubbychin","Routsix Rubbertendon","Ruffbix Jumbolobes","Shisox Widebrow","Slinkix Trufflesniff","Swypestix Tigershins","Tocktix Thinlids","Whistrix Toadthroat","Cobraclaw Buchzvotch","Deathcaller Bidfbid","Drakefeast Wubmfub","Elvaanlopper Grokdok","Galkarider Retzpratz","Heavymail Djidzbad","Humegutter Adzjbadj","Jeunoraider Gepkzip","Lockbuster Zapdjipp","Mithraslaver Debhabob","Skinmask Ugghfogg","Spinalsucker Galflmall","Taruroaster Biggsjig","Ultrasonic Zeknajak","Wraithdancer Gidbnod","Be'Zhe Keeprazer","De'Bho Pyrohand","Ga'Fho Venomtouch","Go'Tyo Magenapper","Gu'Khu Dukesniper","Gu'Nha Wallstormer","Ji'Fhu Infiltrator","Ji'Khu Towercleaver","Mi'Rhe Whisperblade","Mu'Gha Legionkiller","Na'Hya Floodmaker","Nu'Bhi Spiraleye","So'Gho Adderhandler","So'Zho Metalbender","Ta'Hyu Gallanthunter","Bhuu Wjato the Firepool","Caa Xaza the Madpiercer","Foo Peku the Bloodcloak","Guu Waji the Preacher","Hee Mida the Meticulous","Knii Hoqo the Bisector","Koo Saxu the Everfast","Kuu Xuka the Nimble","Maa Zaua the Wyrmkeeper","Nee Huxa the Judgmental","Puu Timu the Phantasmal","Ryy Qihi the Idolrobber","Soo Jopo the Fiendking","Xaa Chau the Roctalon","Xhoo Fuza the Sublime"}},
        [85] = {"Dynamis - Xarcabard",      {"Count Zaebos","Duke Berith","Marquis Decarabia","Duke Gomory","Marquis Andras","Prince Seere","Duke Scox","Marquis Gamygyn","Marquis Orias","Count Raum","Marquis Nebiros","Marquis Sabnak","Count Vine","King Zagan","Marquis Cimeries","Duke Haures","Marquis Caim","Baron Avnas","Count Haagenti"}},
        [86] = {"Ru'Aun Gardens",           {"Byakko","Despot","Genbu","Seiryu","Suzaku"}},
        [87] = {"Ve'Lugannon Palace",       {"Brigandish Blade","Steam Cleaner","Zipacna"}},
        [88] = {"The Shrine of Ru'Avitau",  {"Faust","Kirin","Mother Globe","Olla Grande","Ullikummi"}},
        [89] = {"Al'Taieu",                 {"Om'yovra","Ul'yovra","Jailer of Hope","Jailer of Justice","Jailer of Prudence"}},
        [90] = {"Grand Palace of Hu'Xzoi",  {"Ix'aern (Monk)","Jailer of Temperance"}},
        [91] = {"The Garden of Ru'Hmet",    {"Ix'aern (DRK)","Ix'aern (DRG)","Jailer of Faith","Jailer of Fortitude"}},
        [92] = {"Lufaise Meadows",          {"Amaltheia","Colorful Leshy","Defoliate Leshy","Kurrea","Megalobugard","Padfoot","Flockbock","Sengann","Yal-un Eke"}},
        [93] = {"Misareaux Coast",          {"Goaftrap","Gration","Odqan","Okyupete","Upyri","Ziphius"}},
        [94] = {"Phomiuna Aqueducts",       {"Tres Duendes","Eba","Mahisha"}},
        [95] = {"Sacrarium",                {"Elel"}},
        [96] = {"Riverne Site-A01",         {"Aiatar","Heliodromos","Shieldtrap"}},
        [97] = {"Riverne Site-B01",         {"Boroka","Imdugud","Unstable Cluster"}}
    }

    local handleMidnight = function(player)
        local questMidnight = player:getCharVar("[DailyQuest]Midnight")
        local currentMidnight = getMidnight()

        -- handle first time quest midnight
        if questMidnight == 0 then
            player:setCharVar("[DailyQuest]Midnight", currentMidnight)
            player:setCharVar("[DailyQuest]Completed", 0)
            player:setCharVar("[DailyQuest]Fishstix", 0)
            player:setCharVar("[DailyQuest]Fishstix_zone", 0)
            player:setCharVar("[DailyQuest]Murdoc", 0)
            player:setCharVar("[DailyQuest]Murdoc_zone", 0)
            player:setCharVar("[DailyQuest]Murdoc_mobType", 0)
            player:setCharVar("[DailyQuest]Murdoc_killAmt", 0)
            player:setCharVar("[DailyQuest]Mistrix", 0)
            player:setCharVar("[DailyQuest]Mistrix_item", 0)
            player:setCharVar("[DailyQuest]Saltlik", 0)
            player:setCharVar("[DailyQuest]Saltlik_zone", 0)
            player:setCharVar("[DailyQuest]Saltlik_NM", 0)
            player:setCharVar("[DailyQuest]Beetrix", 0)
            player:setCharVar("[DailyQuest]Beetrix_zone", 0)
            player:setCharVar("[DailyQuest]Beetrix_RExItem", 0)
        end
        
        -- handle midnight reset
        if currentMidnight < questMidnight then
            player:setCharVar("[DailyQuest]Midnight", currentMidnight)
            player:setCharVar("[DailyQuest]Completed", 0)
            player:setCharVar("[DailyQuest]Fishstix", 0)
            player:setCharVar("[DailyQuest]Fishstix_zone", 0)
            player:setCharVar("[DailyQuest]Murdoc", 0)
            player:setCharVar("[DailyQuest]Murdoc_zone", 0)
            player:setCharVar("[DailyQuest]Murdoc_mobType", 0)
            player:setCharVar("[DailyQuest]Murdoc_killAmt", 0)
            player:setCharVar("[DailyQuest]Mistrix", 0)
            player:setCharVar("[DailyQuest]Mistrix_item", 0)
            player:setCharVar("[DailyQuest]Saltlik", 0)
            player:setCharVar("[DailyQuest]Saltlik_zone", 0)
            player:setCharVar("[DailyQuest]Saltlik_NM", 0)
            player:setCharVar("[DailyQuest]Beetrix", 0)
            player:setCharVar("[DailyQuest]Beetrix_zone", 0)
            player:setCharVar("[DailyQuest]Beetrix_RExItem", 0)
        end
    end

    local saltlik = zone:insertDynamicEntity({

        objtype = xi.objType.NPC,
        name = "Saltlik",
        look = 492,
        x = -51.7539,
        y = 0.000,
        z = -58.3718,
        rotation = 19,
        widescan = 1,

        onTrade = function(player, npc, trade)
            player:PrintToPlayer("I don't require any items from you.", 0, npc:getPacketName())
        end,

        onTrigger = function(player, npc)
            handleMidnight(player)
            local questStage = player:getCharVar("[DailyQuest]Saltlik")
            local completedDailyQuests = player:getCharVar("[DailyQuest]Completed")
            
            -- handle quest stages
            if questStage == 0 then
                local randNum = math.random(1,97)
                local questZoneName = questLocations[randNum][1]
                local nmListLength = table.getn(questLocations[randNum][2])
                local randNM = math.random(1,nmListLength)
                local questNMName = questLocations[randNum][2][randNM]
                player:setCharVar("[DailyQuest]Saltlik",1)
                player:setCharVar("[DailyQuest]Saltlik_zone",randNum)
                player:setCharVar("[DailyQuest]Saltlik_NM",randNM)
                player:PrintToPlayer(string.format("Go to %s and kill %s!",questZoneName, questNMName), 0, npc:getPacketName())
                return
            elseif questStage == 1 then
                local questZone = player:getCharVar("[DailyQuest]Saltlik_zone")
                local questNM = player:getCharVar("[DailyQuest]Saltlik_NM")
                local questZoneName = questLocations[questZone][1]
                local questNMName = questLocations[questZone][2][questNM]
                player:PrintToPlayer(string.format("Go to %s and kill %s!",questZoneName, questNMName), 0, npc:getPacketName())
                return
            elseif questStage == 2 then
                player:setCharVar("[DailyQuest]Saltlik",3)
                player:setCharVar("[DailyQuest]Completed",completedDailyQuests + 1)
                player:PrintToPlayer("Congratulations! You've completed my quest for today, here's your reward!", 0, npc:getPacketName())
                player:addCurrency('bayld', 4)
                player:PrintToPlayer("You have obtained 4 bayld!", 17)
                return
            elseif questStage == 3 then
                player:PrintToPlayer("You've already completed this quest today! Come back tomorrow for more.", 0, npc:getPacketName())
                return
            end
        end,
    })

    utils.unused(saltlik)

    local dailyNMs =
    {
        { 1, 1, "West_Ronfaure", "Amanita" },
        { 1, 2, "West_Ronfaure", "Jaggedy-Eared_Jack" },
        { 1, 3, "West_Ronfaure", "Fungus_Beetle" },
        { 2, 1, "East_Ronfaure", "Bigmouth_Billy" },
        { 2, 2, "East_Ronfaure", "Swamfisk" },
        { 2, 3, "East_Ronfaure", "Rambukk" },
        { 3, 1, "South_Gustaberg", "Tococo" },
        { 3, 2, "South_Gustaberg", "Leaping_Lizzy" },
        { 3, 3, "South_Gustaberg", "Carnero" },
        { 4, 1, "North_Gustaberg", "Stinging_Sophie" },
        { 4, 2, "North_Gustaberg", "Maighdean_Uaine" },
        { 4, 3, "North_Gustaberg", "Bedrock_Barry" },
        { 5, 1, "West_Sarutabaruta", "Numbing_Norman" },
        { 5, 2, "West_Sarutabaruta", "Nunyenunc" },
        { 5, 3, "West_Sarutabaruta", "Tom_Tit_Tat" },
        { 6, 1, "East_Sarutabaruta", "Duke_Decapod" },
        { 6, 2, "East_Sarutabaruta", "Spiny_Spipi" },
        { 6, 3, "East_Sarutabaruta", "Sharp-Eared_Ropipi" },
        { 7, 1, "La_Theine_Plateau", "Nihniknoovi" },
        { 7, 2, "La_Theine_Plateau", "Slumbering_Samwell" },
        { 7, 3, "La_Theine_Plateau", "Tumbling_Truffle" },
        { 7, 4, "La_Theine_Plateau", "Lumbering_Lambert" },
        { 7, 5, "La_Theine_Plateau", "Bloodtear_Baldurf" },
        { 8, 1, "Konschtat_Highlands", "Ghillie_Dhu" },
        { 8, 2, "Konschtat_Highlands", "Highlander_Lizard" },
        { 8, 3, "Konschtat_Highlands", "Rampaging_Ram" },
        { 8, 4, "Konschtat_Highlands", "Steelfleece_Baldarich" },
        { 8, 5, "Konschtat_Highlands", "Stray_Mary" },
        { 9, 1, "Tahrongi_Canyon", "Yara_Ma_Yha_Who" },
        { 9, 2, "Tahrongi_Canyon", "Habrok" },
        { 9, 3, "Tahrongi_Canyon", "Serpopard_Ishtar" },
        { 9, 4, "Tahrongi_Canyon", "Herbage_Hunter" },
        { 10, 1, "Valkurm_Dunes", "Metal_Shears" },
        { 10, 2, "Valkurm_Dunes", "Golden_Bat" },
        { 10, 3, "Valkurm_Dunes", "Valkurm_Emperor" },
        { 10, 4, "Valkurm_Dunes", "Hippomaritimus" },
        { 11, 1, "Jugner_Forest", "Panzer_Percival" },
        { 11, 2, "Jugner_Forest", "Fraelissa" },
        { 11, 3, "Jugner_Forest", "Meteormauler_Zhagtegg" },
        { 11, 4, "Jugner_Forest", "Sappy_Sycamore" },
        { 11, 5, "Jugner_Forest", "Supplespine_Mujwuj" },
        { 12, 1, "Batallia_Downs", "Tottering_Toby" },
        { 12, 2, "Batallia_Downs", "Weeping_Willow" },
        { 12, 3, "Batallia_Downs", "Eyegouger" },
        { 12, 4, "Batallia_Downs", "Ahtu" },
        { 12, 5, "Batallia_Downs", "Lumber_Jack" },
        { 12, 6, "Batallia_Downs", "Prankster_Maverix" },
        { 12, 7, "Batallia_Downs", "Skirling_Liger" },
        { 13, 1, "Pashhow_Marshlands", "Bloodpool_Vorax" },
        { 13, 2, "Pashhow_Marshlands", "BoWho_Warmonger" },
        { 13, 3, "Pashhow_Marshlands", "Jolly_Green" },
        { 13, 4, "Pashhow_Marshlands", "Toxic_Tamlyn" },
        { 13, 5, "Pashhow_Marshlands", "NiZho_Bladebender" },
        { 14, 1, "Rolanberry_Fields", "Black_Triple_Stars" },
        { 14, 2, "Rolanberry_Fields", "Drooling_Daisy" },
        { 14, 3, "Rolanberry_Fields", "Silk_Caterpillar" },
        { 14, 4, "Rolanberry_Fields", "Ravenous_Crawler" },
        { 14, 5, "Rolanberry_Fields", "Eldritch_Edge" },
        { 15, 1, "Sauromugue_Champaign", "Deadly_Dodo" },
        { 15, 2, "Sauromugue_Champaign", "Bashe" },
        { 15, 3, "Sauromugue_Champaign", "Thunderclaw_Thuban" },
        { 15, 4, "Sauromugue_Champaign", "Blighting_Brand" },
        { 16, 1, "Beaucedine_Glacier", "Calcabrina" },
        { 16, 2, "Beaucedine_Glacier", "Gargantua" },
        { 16, 3, "Beaucedine_Glacier", "Humbaba" },
        { 16, 4, "Beaucedine_Glacier", "Kirata" },
        { 16, 5, "Beaucedine_Glacier", "Nue" },
        { 17, 1, "Xarcabard", "Barbaric_Weapon" },
        { 17, 2, "Xarcabard", "Duke_Focalor" },
        { 17, 3, "Xarcabard", "Ereshkigal" },
        { 17, 4, "Xarcabard", "Shadow_Eye" },
        { 17, 5, "Xarcabard", "Timeworn_Warrior" },
        { 18, 1, "Cape_Teriggan", "Frostmane" },
        { 18, 2, "Cape_Teriggan", "Kreutzet" },
        { 18, 3, "Cape_Teriggan", "Killer_Jonny" },
        { 18, 4, "Cape_Teriggan", "Tegmine" },
        { 18, 5, "Cape_Teriggan", "Zmey_Gorynych" },
        { 19, 1, "Eastern_Altepa_Desert", "Centurio_XII-I" },
        { 19, 2, "Eastern_Altepa_Desert", "Donnergugi" },
        { 19, 3, "Eastern_Altepa_Desert", "Dune_Widow" },
        { 19, 4, "Eastern_Altepa_Desert", "Nandi" },
        { 20, 1, "Western_Altepa_Desert", "Cactuar_Cantautor" },
        { 20, 2, "Western_Altepa_Desert", "Calchas" },
        { 20, 3, "Western_Altepa_Desert", "Celphie" },
        { 20, 4, "Western_Altepa_Desert", "Dahu" },
        { 20, 5, "Western_Altepa_Desert", "Picolaton" },
        { 21, 1, "Meriphataud_Mountains", "Daggerclaw_Dracos" },
        { 21, 2, "Meriphataud_Mountains", "Patripatan" },
        { 21, 3, "Meriphataud_Mountains", "Chonchon" },
        { 21, 4, "Meriphataud_Mountains", "Waraxe_Beak" },
        { 21, 5, "Meriphataud_Mountains", "Naa_Zeku_the_Unwaiting" },
        { 22, 1, "Buburimu_Peninsula", "Backoo" },
        { 22, 2, "Buburimu_Peninsula", "Buburimboo" },
        { 22, 3, "Buburimu_Peninsula", "Helldiver" },
        { 22, 4, "Buburimu_Peninsula", "Wake_Warder_Wanda" },
        { 23, 1, "The_Sanctuary_of_ZiTah", "Bastet" },
        { 23, 2, "The_Sanctuary_of_ZiTah", "Elusive_Edwin" },
        { 23, 3, "The_Sanctuary_of_ZiTah", "Huwasi" },
        { 23, 4, "The_Sanctuary_of_ZiTah", "Keeper_of_Halidom" },
        { 23, 5, "The_Sanctuary_of_ZiTah", "Noble_Mold" },
        { 24, 1, "RoMaeve", "Nightmare_Vase" },
        { 24, 2, "RoMaeve", "Martinet" },
        { 24, 3, "RoMaeve", "Nargun" },
        { 24, 4, "RoMaeve", "Rogue_Receptacle" },
        { 25, 1, "Yuhtunga_Jungle", "Bayawak" },
        { 25, 2, "Yuhtunga_Jungle", "Koropokkur" },
        { 25, 3, "Yuhtunga_Jungle", "Meww_the_Turtlerider" },
        { 25, 4, "Yuhtunga_Jungle", "Mischievous_Micholas" },
        { 25, 5, "Yuhtunga_Jungle", "Pyuu_the_Spatemaker" },
        { 25, 6, "Yuhtunga_Jungle", "Rose_Garden" },
        { 25, 7, "Yuhtunga_Jungle", "Voluptuous_Vilma" },
        { 26, 1, "Yhoator_Jungle", "Acolnahuacatl" },
        { 26, 2, "Yhoator_Jungle", "Bisque-heeled_Sunberry" },
        { 26, 3, "Yhoator_Jungle", "Bright-handed_Kunberry" },
        { 26, 4, "Yhoator_Jungle", "Edacious_Opo-opo" },
        { 26, 5, "Yhoator_Jungle", "Hoar-knuckled_Rimberry" },
        { 26, 6, "Yhoator_Jungle", "Powderer_Penny" },
        { 26, 7, "Yhoator_Jungle", "Woodland_Sage" },
        { 27, 1, "Qufim_Island", "Dosetsu_Tree" },
        { 27, 2, "Qufim_Island", "Slippery_Sucker" },
        { 27, 3, "Qufim_Island", "Trickster_Kinetix" },
        { 27, 4, "Qufim_Island", "Atkorkamuy" },
        { 27, 5, "Qufim_Island", "Qoofim" },
        { 28, 1, "Temple_of_Uggalepih", "Bonze_Marberry" },
        { 28, 2, "Temple_of_Uggalepih", "Death_from_Above" },
        { 28, 3, "Temple_of_Uggalepih", "Flauros" },
        { 28, 4, "Temple_of_Uggalepih", "Habetrot" },
        { 28, 5, "Temple_of_Uggalepih", "Manipulator" },
        { 28, 6, "Temple_of_Uggalepih", "Sacrificial_Goblet" },
        { 28, 7, "Temple_of_Uggalepih", "Sozu_Terberry" },
        { 28, 8, "Temple_of_Uggalepih", "Tonberry_Kinq" },
        { 29, 1, "Valley_of_Sorrows", "Adamantoise" },
        { 30, 1, "Bibiki_Bay", "Intulo" },
        { 30, 2, "Bibiki_Bay", "Splacknuck" },
        { 30, 3, "Bibiki_Bay", "Shankha" },
        { 30, 4, "Bibiki_Bay", "Serra" },
        { 31, 1, "Carpenters_Landing", "Hercules_Beetle" },
        { 31, 2, "Carpenters_Landing", "Mycophile" },
        { 31, 3, "Carpenters_Landing", "Orctrap" },
        { 31, 4, "Carpenters_Landing", "Tempest_Tigon" },
        { 32, 1, "Uleguerand_Range", "Black_Coney" },
        { 32, 2, "Uleguerand_Range", "Bonnacon" },
        { 32, 3, "Uleguerand_Range", "Father_Frost" },
        { 32, 4, "Uleguerand_Range", "Geush_Urvan" },
        { 32, 5, "Uleguerand_Range", "Magnotaur" },
        { 32, 6, "Uleguerand_Range", "Mountain_Worm" },
        { 32, 7, "Uleguerand_Range", "Skvader" },
        { 32, 8, "Uleguerand_Range", "Snow_Maiden" },
        { 32, 9, "Uleguerand_Range", "White_Coney" },
        { 33, 1, "Attohwa_Chasm", "Ambusher_Antlion" },
        { 33, 2, "Attohwa_Chasm", "Citipati" },
        { 33, 3, "Attohwa_Chasm", "Sargas" },
        { 33, 4, "Attohwa_Chasm", "Sekhmet" },
        { 34, 1, "Oldton_Movalpolos", "Bugbear_Strongman" },
        { 34, 2, "Oldton_Movalpolos", "Goblin_Wolfman" },
        { 34, 3, "Oldton_Movalpolos", "Bugbear_Muscleman" },
        { 35, 1, "Newton_Movalpolos", "Bugbear_Matman" },
        { 35, 2, "Newton_Movalpolos", "Goblin_Collector" },
        { 35, 3, "Newton_Movalpolos", "Sword_Sorcerer_Solisoq" },
        { 35, 4, "Newton_Movalpolos", "Swashstox_Beadblinker" },
        { 36, 1, "Wajaom_Woodlands", "Gharial" },
        { 36, 2, "Wajaom_Woodlands", "Jaded_Jody" },
        { 36, 3, "Wajaom_Woodlands", "Zoraal_Jas_Pkuucha" },
        { 37, 1, "Bhaflau_Thickets", "Emergent_Elm" },
        { 37, 2, "Bhaflau_Thickets", "Harvestman" },
        { 37, 3, "Bhaflau_Thickets", "Mahishasura" },
        { 37, 4, "Bhaflau_Thickets", "Nis_Puk" },
        { 38, 1, "Arrapago_Reef", "Bloody_Bones" },
        { 38, 2, "Arrapago_Reef", "Euryale" },
        { 38, 3, "Arrapago_Reef", "Lamie_No7" },
        { 38, 4, "Arrapago_Reef", "Lamie_No8" },
        { 38, 5, "Arrapago_Reef", "Lamie_No9" },
        { 38, 6, "Arrapago_Reef", "Lamia_No19" },
        { 38, 7, "Arrapago_Reef", "Merrow_No5" },
        { 39, 1, "Mount_Zhayolm", "Chary_Apkallu" },
        { 39, 2, "Mount_Zhayolm", "Energetic_Eruca" },
        { 39, 3, "Mount_Zhayolm", "Garfurlar_the_Rabid" },
        { 39, 4, "Mount_Zhayolm", "Garharlor_the_Unruly" },
        { 39, 5, "Mount_Zhayolm", "Garhorlur_the_Brutal" },
        { 39, 6, "Mount_Zhayolm", "Fahrafahr_the_Bloodied" },
        { 39, 7, "Mount_Zhayolm", "Ignamoth" },
        { 40, 1, "Halvung", "Copper_Borer" },
        { 40, 2, "Halvung", "Dorgerwor_the_Astute" },
        { 40, 3, "Halvung", "Farlarder_the_Shrewd" },
        { 40, 4, "Halvung", "Flammeri" },
        { 40, 5, "Halvung", "Kirlirger_the_Abhorrent" },
        { 40, 6, "Halvung", "Mythril_Mouth_Monamaq" },
        { 41, 1, "Mamook", "Darting_Kachaal_Ja" },
        { 41, 2, "Mamook", "Devout_Radol_Ja" },
        { 41, 3, "Mamook", "Dragonscaled_Bugaal_Ja" },
        { 41, 4, "Mamook", "Firedance_Magmaal_Ja" },
        { 41, 5, "Mamook", "Hundredfaced_Hapool_Ja" },
        { 41, 6, "Mamook", "Venomfang" },
        { 41, 7, "Mamook", "Zizzy_Zillah" },
        { 42, 1, "Aydeewa_Subterrane", "Bluestreak_Gyugyuroon" },
        { 42, 2, "Aydeewa_Subterrane", "Crystal_Eater" },
        { 42, 3, "Aydeewa_Subterrane", "Lizardtrap" },
        { 43, 1, "Alzadaal_Undersea_Ruins", "Boompadu" },
        { 43, 2, "Alzadaal_Undersea_Ruins", "Cookieduster_Lipiroon" },
        { 43, 3, "Alzadaal_Undersea_Ruins", "Oupire" },
        { 44, 1, "Caedarva_Mire", "Aynu-kaysey" },
        { 44, 2, "Caedarva_Mire", "Peallaidh" },
        { 44, 3, "Caedarva_Mire", "Vidhuwa_the_Wrathborn" },
        { 44, 4, "Caedarva_Mire", "Zikko" },
        { 45, 1, "Yughott_Grotto", "Ashmaker_Gotblut" },
        { 46, 1, "Fort_Ghelsba", "Chariotbuster_Byakzak" },
        { 46, 2, "Fort_Ghelsba", "Hundredscar_Hajwaj" },
        { 46, 3, "Fort_Ghelsba", "Orcish_Panzer" },
        { 46, 4, "Fort_Ghelsba", "Kegpaunch_Doshgnosh" },
        { 47, 1, "Palborough_Mines", "BuGhi_Howlblade" },
        { 47, 2, "Palborough_Mines", "NoMho_Crimsonarmor" },
        { 47, 3, "Palborough_Mines", "ZiGhi_Boneeater" },
        { 47, 4, "Palborough_Mines", "BeHya_Hundredwall" },
        { 47, 5, "Palborough_Mines", "QuVho_Deathhurler" },
        { 48, 1, "Giddeus", "Eyy_Mon_the_Ironbreaker" },
        { 48, 2, "Giddeus", "Hoo_Mjuu_the_Torrent" },
        { 48, 3, "Giddeus", "Juu_Duzu_the_Whirlwind" },
        { 48, 4, "Giddeus", "Quu_Xijo_the_Illusory" },
        { 48, 5, "Giddeus", "Vuu_Puqu_the_Beguiler" },
        { 48, 6, "Giddeus", "Zhuu_Buxu_the_Silent" },
        { 49, 1, "Beadeaux", "BiGho_Headtaker" },
        { 49, 2, "Beadeaux", "DaDha_Hundredmask" },
        { 49, 3, "Beadeaux", "DeVyu_Headhunter" },
        { 49, 4, "Beadeaux", "GaBhu_Unvanquished" },
        { 49, 5, "Beadeaux", "GeDha_Evileye" },
        { 49, 6, "Beadeaux", "GoBhu_Gascon" },
        { 49, 7, "Beadeaux", "ZoKhu_Blackcloud" },
        { 50, 1, "Davoi", "Blubbery_Bulge" },
        { 50, 2, "Davoi", "Dirtyhanded_Gochakzuk" },
        { 50, 3, "Davoi", "Hawkeyed_Dnatbat" },
        { 50, 4, "Davoi", "Poisonhand_Gnadgad" },
        { 50, 5, "Davoi", "Steelbiter_Gudrud" },
        { 50, 6, "Davoi", "Tigerbane_Bakdak" },
        { 51, 1, "Monastic_Cavern", "Orcish_Hexspinner" },
        { 51, 2, "Monastic_Cavern", "Orcish_Overlord" },
        { 51, 3, "Monastic_Cavern", "Orcish_Warlord" },
        { 51, 4, "Monastic_Cavern", "Overlord_Bakgodek" },
        { 52, 1, "Castle_Oztroja", "Moo_Ouzi_the_Swiftblade" },
        { 52, 2, "Castle_Oztroja", "Mee_Deggi_the_Punisher" },
        { 52, 3, "Castle_Oztroja", "Quu_Domi_the_Gallant" },
        { 52, 4, "Castle_Oztroja", "Saa_Doyi_the_Fervid" },
        { 52, 5, "Castle_Oztroja", "Yaa_Haqa_the_Profane" },
        { 52, 6, "Castle_Oztroja", "Yagudo_High_Priest" },
        { 52, 7, "Castle_Oztroja", "Yagudo_Templar" },
        { 52, 8, "Castle_Oztroja", "Lii_Jixa_the_Somnolist" },
        { 53, 1, "The_Boyahda_Tree", "Ancient_Goobbue" },
        { 53, 2, "The_Boyahda_Tree", "Aquarius" },
        { 53, 3, "The_Boyahda_Tree", "Ellyllon" },
        { 53, 4, "The_Boyahda_Tree", "Leshonki" },
        { 53, 5, "The_Boyahda_Tree", "Unut" },
        { 53, 6, "The_Boyahda_Tree", "Voluptuous_Vivian" },
        { 54, 1, "Lower_Delkfutts_Tower", "Epialtes" },
        { 54, 2, "Lower_Delkfutts_Tower", "Eurymedon" },
        { 54, 3, "Lower_Delkfutts_Tower", "Hippolytos" },
        { 54, 4, "Lower_Delkfutts_Tower", "Tyrant" },
        { 55, 1, "Middle_Delkfutts_Tower", "Eurytos" },
        { 55, 2, "Middle_Delkfutts_Tower", "Ogygos" },
        { 55, 3, "Middle_Delkfutts_Tower", "Ophion" },
        { 55, 4, "Middle_Delkfutts_Tower", "Polybotes" },
        { 55, 5, "Middle_Delkfutts_Tower", "Rhoikos" },
        { 55, 6, "Middle_Delkfutts_Tower", "Rhoitos" },
        { 56, 1, "Upper_Delkfutts_Tower", "Alkyoneus" },
        { 56, 2, "Upper_Delkfutts_Tower", "Enkelados" },
        { 56, 3, "Upper_Delkfutts_Tower", "Ixtab" },
        { 56, 4, "Upper_Delkfutts_Tower", "Mimas" },
        { 56, 5, "Upper_Delkfutts_Tower", "Pallas" },
        { 56, 6, "Upper_Delkfutts_Tower", "Porphyrion" },
        { 56, 7, "Upper_Delkfutts_Tower", "Autarch" },
        { 57, 1, "Den_of_Rancor", "Bistre-hearted_Malberry" },
        { 57, 2, "Den_of_Rancor", "Carmine-tailed_Janberry" },
        { 57, 3, "Den_of_Rancor", "Celeste-eyed_Tozberry" },
        { 57, 4, "Den_of_Rancor", "Friar_Rush" },
        { 57, 5, "Den_of_Rancor", "Ogama" },
        { 57, 6, "Den_of_Rancor", "Sozu_Bliberry" },
        { 57, 7, "Den_of_Rancor", "Tawny-fingered_Mugberry" },
        { 57, 8, "Den_of_Rancor", "Tonberry_Decapitator" },
        { 57, 9, "Den_of_Rancor", "Tonberry_Pontifex" },
        { 57, 10, "Den_of_Rancor", "Tonberry_Tracker" },
        { 58, 1, "Castle_Zvahl_Baileys", "Duke_Haborym" },
        { 58, 2, "Castle_Zvahl_Baileys", "Grand_Duke_Batym" },
        { 58, 3, "Castle_Zvahl_Baileys", "Likho" },
        { 58, 4, "Castle_Zvahl_Baileys", "Marquis_Allocen" },
        { 58, 5, "Castle_Zvahl_Baileys", "Marquis_Amon" },
        { 58, 6, "Castle_Zvahl_Baileys", "Marquis_Naberius" },
        { 58, 7, "Castle_Zvahl_Baileys", "Marquis_Sabnock" },
        { 59, 1, "Castle_Zvahl_Keep", "Baron_Vapula" },
        { 59, 2, "Castle_Zvahl_Keep", "Baronet_Romwe" },
        { 59, 3, "Castle_Zvahl_Keep", "Count_Bifrons" },
        { 59, 4, "Castle_Zvahl_Keep", "Viscount_Morax" },
        { 60, 1, "Ranguemont_Pass", "Mucoid_Mass" },
        { 60, 2, "Ranguemont_Pass", "Taisaijin" },
        { 60, 3, "Ranguemont_Pass", "Gloom_Eye" },
        { 60, 4, "Ranguemont_Pass", "Hyakume" },
        { 61, 1, "Bostaunieux_Oubliette", "Arioch" },
        { 61, 2, "Bostaunieux_Oubliette", "Bloodsucker" },
        { 61, 3, "Bostaunieux_Oubliette", "Drexerion_the_Condemned" },
        { 61, 4, "Bostaunieux_Oubliette", "Manes" },
        { 61, 5, "Bostaunieux_Oubliette", "Phanduron_the_Condemned" },
        { 61, 6, "Bostaunieux_Oubliette", "Sewer_Syrup" },
        { 61, 7, "Bostaunieux_Oubliette", "Shii" },
        { 62, 1, "Toraimarai_Canal", "Canal_Moocher" },
        { 62, 2, "Toraimarai_Canal", "Brazen_Bones" },
        { 62, 3, "Toraimarai_Canal", "Konjac" },
        { 63, 1, "Korroloka_Tunnel", "Cargo_Crab_Colin" },
        { 63, 2, "Korroloka_Tunnel", "Dame_Blanche" },
        { 63, 3, "Korroloka_Tunnel", "Falcatus_Aranei" },
        { 63, 4, "Korroloka_Tunnel", "Morion_Worm" },
        { 63, 5, "Korroloka_Tunnel", "Thoon" },
        { 64, 1, "Kuftal_Tunnel", "Amemet" },
        { 64, 2, "Kuftal_Tunnel", "Arachne" },
        { 64, 3, "Kuftal_Tunnel", "Bloodthirster_Madkix" },
        { 64, 4, "Kuftal_Tunnel", "Cancer" },
        { 64, 5, "Kuftal_Tunnel", "Guivre" },
        { 64, 6, "Kuftal_Tunnel", "Pelican" },
        { 64, 7, "Kuftal_Tunnel", "Phantom_Worm" },
        { 64, 8, "Kuftal_Tunnel", "Sabotender_Mariachi" },
        { 64, 9, "Kuftal_Tunnel", "Yowie" },
        { 65, 1, "The_Eldieme_Necropolis", "Cwn_Cyrff" },
        { 65, 2, "The_Eldieme_Necropolis", "Skull_of_Envy" },
        { 65, 3, "The_Eldieme_Necropolis", "Skull_of_Gluttony" },
        { 65, 4, "The_Eldieme_Necropolis", "Skull_of_Greed" },
        { 65, 5, "The_Eldieme_Necropolis", "Skull_of_Lust" },
        { 65, 6, "The_Eldieme_Necropolis", "Skull_of_Pride" },
        { 65, 7, "The_Eldieme_Necropolis", "Skull_of_Sloth" },
        { 65, 8, "The_Eldieme_Necropolis", "Skull_of_Wrath" },
        { 66, 1, "Sea_Serpent_Grotto", "Abyss_Sahagin" },
        { 66, 2, "Sea_Serpent_Grotto", "Coral_Sahagin" },
        { 66, 3, "Sea_Serpent_Grotto", "Denn_the_Orcavoiced" },
        { 66, 4, "Sea_Serpent_Grotto", "Fyuu_the_Seabellow" },
        { 66, 5, "Sea_Serpent_Grotto", "Masan" },
        { 66, 6, "Sea_Serpent_Grotto", "Mouu_the_Waverider" },
        { 66, 7, "Sea_Serpent_Grotto", "Namtar" },
        { 66, 8, "Sea_Serpent_Grotto", "Novv_the_Whitehearted" },
        { 66, 9, "Sea_Serpent_Grotto", "Ocean_Sahagin" },
        { 66, 10, "Sea_Serpent_Grotto", "Pahh_the_Gullcaller" },
        { 66, 11, "Sea_Serpent_Grotto", "Qull_the_Shellbuster" },
        { 66, 12, "Sea_Serpent_Grotto", "Sea_Hog" },
        { 66, 13, "Sea_Serpent_Grotto", "Seww_the_Squidlimbed" },
        { 66, 14, "Sea_Serpent_Grotto", "Voll_the_Sharkfinned" },
        { 66, 15, "Sea_Serpent_Grotto", "Worr_the_Clawfisted" },
        { 66, 16, "Sea_Serpent_Grotto", "Wuur_the_Sandcomber" },
        { 66, 17, "Sea_Serpent_Grotto", "Yarr_the_Pearleyed" },
        { 66, 18, "Sea_Serpent_Grotto", "Zuug_the_Shoreleaper" },
        { 67, 1, "Dangruf_Wadi", "Chocoboleech" },
        { 67, 2, "Dangruf_Wadi", "Geyser_Lizard" },
        { 67, 3, "Dangruf_Wadi", "Teporingo" },
        { 68, 1, "Inner_Horutoto_Ruins", "Maltha" },
        { 68, 2, "Inner_Horutoto_Ruins", "Nocuous_Weapon" },
        { 68, 3, "Inner_Horutoto_Ruins", "Slendlix_Spindlethumb" },
        { 69, 1, "Outer_Horutoto_Ruins", "Bomb_King" },
        { 69, 2, "Outer_Horutoto_Ruins", "Doppelganger_Dio" },
        { 69, 3, "Outer_Horutoto_Ruins", "Doppelganger_Gog" },
        { 69, 4, "Outer_Horutoto_Ruins", "Legalox_Heftyhind" },
        { 69, 5, "Outer_Horutoto_Ruins", "Ah_Puch" },
        { 69, 6, "Outer_Horutoto_Ruins", "Desmodont" },
        { 70, 1, "Ordelles_Caves", "Aroma_Leech" },
        { 70, 2, "Ordelles_Caves", "Bombast" },
        { 70, 3, "Ordelles_Caves", "Donggu" },
        { 70, 4, "Ordelles_Caves", "Morbolger" },
        { 70, 5, "Ordelles_Caves", "Agar_Agar" },
        { 71, 1, "Gusgen_Mines", "Aroma_Fly" },
        { 71, 2, "Gusgen_Mines", "Asphyxiated_Amsel" },
        { 71, 3, "Gusgen_Mines", "Burned_Bergmann" },
        { 71, 4, "Gusgen_Mines", "Crushed_Krause" },
        { 71, 5, "Gusgen_Mines", "Juggler_Hecatomb" },
        { 71, 6, "Gusgen_Mines", "Pulverized_Pfeffer" },
        { 71, 7, "Gusgen_Mines", "Smothered_Schmidt" },
        { 71, 8, "Gusgen_Mines", "Wounded_Wurfel" },
        { 72, 1, "Crawlers_Nest", "Aqrabuamelu" },
        { 72, 2, "Crawlers_Nest", "Awd_Goggie" },
        { 72, 3, "Crawlers_Nest", "Demonic_Tiphia" },
        { 72, 4, "Crawlers_Nest", "Drone_Crawler" },
        { 72, 5, "Crawlers_Nest", "Dynast_Beetle" },
        { 72, 6, "Crawlers_Nest", "Guardian_Crawler" },
        { 72, 7, "Crawlers_Nest", "Matron_Crawler" },
        { 72, 8, "Crawlers_Nest", "Queen_Crawler" },
        { 73, 1, "Maze_of_Shakhrami", "Lesath" },
        { 73, 2, "Maze_of_Shakhrami", "Aroma_Crawler" },
        { 73, 3, "Maze_of_Shakhrami", "Gloombound_Lurker" },
        { 73, 4, "Maze_of_Shakhrami", "Trembler_Tabitha" },
        { 74, 1, "Garlaige_Citadel", "Frogamander" },
        { 74, 2, "Garlaige_Citadel", "Hazmat" },
        { 74, 3, "Garlaige_Citadel", "Old_Two-Wings" },
        { 74, 4, "Garlaige_Citadel", "Hovering_Hotpot" },
        { 75, 1, "FeiYin", "Capricious_Cassie" },
        { 75, 2, "FeiYin", "Eastern_Shadow" },
        { 75, 3, "FeiYin", "Goliath" },
        { 75, 4, "FeiYin", "Jenglot" },
        { 75, 5, "FeiYin", "Mind_Hoarder" },
        { 75, 6, "FeiYin", "Northern_Shadow" },
        { 75, 7, "FeiYin", "Sluagh" },
        { 75, 8, "FeiYin", "Southern_Shadow" },
        { 75, 9, "FeiYin", "Western_Shadow" },
        { 76, 1, "Ifrits_Cauldron", "Ash_Dragon" },
        { 76, 2, "Ifrits_Cauldron", "Bomb_Queen" },
        { 76, 3, "Ifrits_Cauldron", "Foreseer_Oramix" },
        { 76, 4, "Ifrits_Cauldron", "Lindwurm" },
        { 76, 5, "Ifrits_Cauldron", "Tarasque" },
        { 76, 6, "Ifrits_Cauldron", "Tyrannic_Tunnok" },
        { 76, 7, "Ifrits_Cauldron", "Vouivre" },
        { 77, 1, "Quicksand_Caves", "Antican_Consul" },
        { 77, 2, "Quicksand_Caves", "Antican_Legatus" },
        { 77, 3, "Quicksand_Caves", "Antican_Magister" },
        { 77, 4, "Quicksand_Caves", "Antican_Praefectus" },
        { 77, 5, "Quicksand_Caves", "Antican_Praetor" },
        { 77, 6, "Quicksand_Caves", "Antican_Proconsul" },
        { 77, 7, "Quicksand_Caves", "Antican_Tribunus" },
        { 77, 8, "Quicksand_Caves", "Centurio_X-I" },
        { 77, 9, "Quicksand_Caves", "Diamond_Daig" },
        { 77, 10, "Quicksand_Caves", "Hastatus_XI-XII" },
        { 77, 11, "Quicksand_Caves", "Nussknacker" },
        { 77, 12, "Quicksand_Caves", "Proconsul_XII" },
        { 77, 13, "Quicksand_Caves", "Sabotender_Bailarin" },
        { 77, 14, "Quicksand_Caves", "Sabotender_Bailarina" },
        { 77, 15, "Quicksand_Caves", "Sagittarius_X-XIII" },
        { 77, 16, "Quicksand_Caves", "Triarius_X-XV" },
        { 77, 17, "Quicksand_Caves", "Tribunus_VII-I" },
        { 78, 1, "Gustav_Tunnel", "Amikiri" },
        { 78, 2, "Gustav_Tunnel", "Baobhan_Sith" },
        { 78, 3, "Gustav_Tunnel", "Bune" },
        { 78, 4, "Gustav_Tunnel", "Goblinsavior_Heronox" },
        { 78, 5, "Gustav_Tunnel", "Taxim" },
        { 78, 6, "Gustav_Tunnel", "Ungur" },
        { 78, 7, "Gustav_Tunnel", "Wyvernpoacher_Drachlox" },
        { 79, 1, "Labyrinth_of_Onzozo", "Hellion" },
        { 79, 2, "Labyrinth_of_Onzozo", "Mysticmaker_Profblix" },
        { 79, 3, "Labyrinth_of_Onzozo", "Narasimha" },
        { 79, 4, "Labyrinth_of_Onzozo", "Ose" },
        { 79, 5, "Labyrinth_of_Onzozo", "Peg_Powler" },
        { 79, 6, "Labyrinth_of_Onzozo", "Soulstealer_Skullnix" },
        { 80, 1, "Dynamis-Bastok", "AaNyu_Dismantler" },
        { 80, 2, "Dynamis-Bastok", "BeEbo_Tortoisedriver" },
        { 80, 3, "Dynamis-Bastok", "GuNhi_Noondozer" },
        { 80, 4, "Dynamis-Bastok", "GiPha_Manameister" },
        { 80, 5, "Dynamis-Bastok", "KoDho_Cannonball" },
        { 80, 6, "Dynamis-Bastok", "ZeVho_Fallsplitter" },
        { 80, 7, "Dynamis-Bastok", "GuDha_Effigy" },
        { 80, 8, "Dynamis-Bastok", "ZoPha_Forgesoul" },
        { 80, 9, "Dynamis-Bastok", "RaGho_Darkfount" },
        { 80, 10, "Dynamis-Bastok", "VaZhe_Pummelsong" },
        { 80, 11, "Dynamis-Bastok", "BuBho_Truesteel" },
        { 81, 1, "Dynamis-San_dOria", "Reapertongue_Gadgquok" },
        { 81, 2, "Dynamis-San_dOria", "Voidstreaker_Butchnotch" },
        { 81, 3, "Dynamis-San_dOria", "Wyrmgnasher_Bjakdek" },
        { 81, 4, "Dynamis-San_dOria", "Battlechoir_Gitchfotch" },
        { 81, 5, "Dynamis-San_dOria", "Soulsender_Fugbrag" },
        { 81, 6, "Dynamis-San_dOria", "Bladeburner_Rokgevok" },
        { 81, 7, "Dynamis-San_dOria", "Steelshank_Kratzvatz" },
        { 81, 8, "Dynamis-San_dOria", "Bloodfist_Voshgrosh" },
        { 81, 9, "Dynamis-San_dOria", "Spellspear_Djokvukk" },
        { 82, 1, "Dynamis-Windurst", "Haa_Pevi_the_Stentorian" },
        { 82, 2, "Dynamis-Windurst", "Loo_Hepe_the_Eyepiercer" },
        { 82, 3, "Dynamis-Windurst", "Wuu_Qoho_the_Razorclaw" },
        { 82, 4, "Dynamis-Windurst", "Xoo_Kaza_the_Solemn" },
        { 82, 5, "Dynamis-Windurst", "Xuu_Bhoqa_the_Enigma" },
        { 82, 6, "Dynamis-Windurst", "Fuu_Tzapo_the_Blessed" },
        { 82, 7, "Dynamis-Windurst", "Naa_Yixo_the_Stillrage" },
        { 82, 8, "Dynamis-Windurst", "Tee_Zaksa_the_Ceaseless" },
        { 82, 9, "Dynamis-Windurst", "Maa_Febi_the_Steadfast" },
        { 83, 1, "Dynamis-Jeuno", "Bandrix_Rockjaw" },
        { 83, 2, "Dynamis-Jeuno", "Buffrix_Eargone" },
        { 83, 3, "Dynamis-Jeuno", "Cloktix_Longnail" },
        { 83, 4, "Dynamis-Jeuno", "Elixmix_Hooknose" },
        { 83, 5, "Dynamis-Jeuno", "Gabblox_Magpietongue" },
        { 83, 6, "Dynamis-Jeuno", "Hermitrix_Toothrot" },
        { 83, 7, "Dynamis-Jeuno", "Humnox_Drumbelly" },
        { 83, 8, "Dynamis-Jeuno", "Lurklox_Dhalmelneck" },
        { 83, 9, "Dynamis-Jeuno", "Morgmox_Moldnoggin" },
        { 83, 10, "Dynamis-Jeuno", "Sparkspox_Sweatbrow" },
        { 83, 11, "Dynamis-Jeuno", "Ticktox_Beadyeyes" },
        { 83, 12, "Dynamis-Jeuno", "Trailblix_Goatmug" },
        { 83, 13, "Dynamis-Jeuno", "Tufflix_Loglimbs" },
        { 83, 14, "Dynamis-Jeuno", "Wyrmwix_Snakespecs" },
        { 83, 15, "Dynamis-Jeuno", "Karashix_Swollenskull" },
        { 83, 16, "Dynamis-Jeuno", "Kikklix_Longlegs" },
        { 83, 17, "Dynamis-Jeuno", "Rutrix_Hamgams" },
        { 83, 18, "Dynamis-Jeuno", "Snypestix_Eaglebeak" },
        { 83, 19, "Dynamis-Jeuno", "Mortilox_Wartpaws" },
        { 83, 20, "Dynamis-Jeuno", "Jabkix_Pigeonpecs" },
        { 83, 21, "Dynamis-Jeuno", "Smeltix_Thickhide" },
        { 83, 22, "Dynamis-Jeuno", "Wasabix_Callusdigit" },
        { 83, 23, "Dynamis-Jeuno", "Anvilix_Sootwrists" },
        { 83, 24, "Dynamis-Jeuno", "Blazox_Boneybod" },
        { 83, 25, "Dynamis-Jeuno", "Bootrix_Jaggedelbow" },
        { 83, 26, "Dynamis-Jeuno", "Distilix_Stickytoes" },
        { 83, 27, "Dynamis-Jeuno", "Eremix_Snottynostril" },
        { 83, 28, "Dynamis-Jeuno", "Jabbrox_Grannyguise" },
        { 83, 29, "Dynamis-Jeuno", "Mobpix_Mucousmouth" },
        { 83, 30, "Dynamis-Jeuno", "Prowlox_Barrelbelly" },
        { 83, 31, "Dynamis-Jeuno", "Scruffix_Shaggychest" },
        { 83, 32, "Dynamis-Jeuno", "Slystix_Megapeepers" },
        { 83, 33, "Dynamis-Jeuno", "Tymexox_Ninefingers" },
        { 83, 34, "Dynamis-Jeuno", "Quicktrix_Hexhands" },
        { 83, 35, "Dynamis-Jeuno", "Feralox_Honeylips" },
        { 83, 36, "Dynamis-Jeuno", "Scourquix_Scaleskin" },
        { 83, 37, "Dynamis-Jeuno", "Wilywox_Tenderpalm" },
        { 84, 1, "Dynamis-Beaucedine", "Ascetox_Ratgums" },
        { 84, 2, "Dynamis-Beaucedine", "Bordox_Kittyback" },
        { 84, 3, "Dynamis-Beaucedine", "Brewnix_Bittypupils" },
        { 84, 4, "Dynamis-Beaucedine", "Draklix_Scalecrust" },
        { 84, 5, "Dynamis-Beaucedine", "Droprix_Granitepalms" },
        { 84, 6, "Dynamis-Beaucedine", "Gibberox_Pimplebeak" },
        { 84, 7, "Dynamis-Beaucedine", "Moltenox_Stubthumbs" },
        { 84, 8, "Dynamis-Beaucedine", "Morblox_Chubbychin" },
        { 84, 9, "Dynamis-Beaucedine", "Routsix_Rubbertendon" },
        { 84, 10, "Dynamis-Beaucedine", "Ruffbix_Jumbolobes" },
        { 84, 11, "Dynamis-Beaucedine", "Shisox_Widebrow" },
        { 84, 12, "Dynamis-Beaucedine", "Slinkix_Trufflesniff" },
        { 84, 13, "Dynamis-Beaucedine", "Swypestix_Tigershins" },
        { 84, 14, "Dynamis-Beaucedine", "Tocktix_Thinlids" },
        { 84, 15, "Dynamis-Beaucedine", "Whistrix_Toadthroat" },
        { 84, 16, "Dynamis-Beaucedine", "Cobraclaw_Buchzvotch" },
        { 84, 17, "Dynamis-Beaucedine", "Deathcaller_Bidfbid" },
        { 84, 18, "Dynamis-Beaucedine", "Drakefeast_Wubmfub" },
        { 84, 19, "Dynamis-Beaucedine", "Elvaanlopper_Grokdok" },
        { 84, 20, "Dynamis-Beaucedine", "Galkarider_Retzpratz" },
        { 84, 21, "Dynamis-Beaucedine", "Heavymail_Djidzbad" },
        { 84, 22, "Dynamis-Beaucedine", "Humegutter_Adzjbadj" },
        { 84, 23, "Dynamis-Beaucedine", "Jeunoraider_Gepkzip" },
        { 84, 24, "Dynamis-Beaucedine", "Lockbuster_Zapdjipp" },
        { 84, 25, "Dynamis-Beaucedine", "Mithraslaver_Debhabob" },
        { 84, 26, "Dynamis-Beaucedine", "Skinmask_Ugghfogg" },
        { 84, 27, "Dynamis-Beaucedine", "Spinalsucker_Galflmall" },
        { 84, 28, "Dynamis-Beaucedine", "Taruroaster_Biggsjig" },
        { 84, 29, "Dynamis-Beaucedine", "Ultrasonic_Zeknajak" },
        { 84, 30, "Dynamis-Beaucedine", "Wraithdancer_Gidbnod" },
        { 84, 31, "Dynamis-Beaucedine", "BeZhe_Keeprazer" },
        { 84, 32, "Dynamis-Beaucedine", "DeBho_Pyrohand" },
        { 84, 33, "Dynamis-Beaucedine", "GaFho_Venomtouch" },
        { 84, 34, "Dynamis-Beaucedine", "GoTyo_Magenapper" },
        { 84, 35, "Dynamis-Beaucedine", "GuKhu_Dukesniper" },
        { 84, 36, "Dynamis-Beaucedine", "GuNha_Wallstormer" },
        { 84, 37, "Dynamis-Beaucedine", "JiFhu_Infiltrator" },
        { 84, 38, "Dynamis-Beaucedine", "JiKhu_Towercleaver" },
        { 84, 39, "Dynamis-Beaucedine", "MiRhe_Whisperblade" },
        { 84, 40, "Dynamis-Beaucedine", "MuGha_Legionkiller" },
        { 84, 41, "Dynamis-Beaucedine", "NaHya_Floodmaker" },
        { 84, 42, "Dynamis-Beaucedine", "NuBhi_Spiraleye" },
        { 84, 43, "Dynamis-Beaucedine", "SoGho_Adderhandler" },
        { 84, 44, "Dynamis-Beaucedine", "SoZho_Metalbender" },
        { 84, 45, "Dynamis-Beaucedine", "TaHyu_Gallanthunter" },
        { 84, 46, "Dynamis-Beaucedine", "Bhuu_Wjato_the_Firepool" },
        { 84, 47, "Dynamis-Beaucedine", "Caa_Xaza_the_Madpiercer" },
        { 84, 48, "Dynamis-Beaucedine", "Foo_Peku_the_Bloodcloak" },
        { 84, 49, "Dynamis-Beaucedine", "Guu_Waji_the_Preacher" },
        { 84, 50, "Dynamis-Beaucedine", "Hee_Mida_the_Meticulous" },
        { 84, 51, "Dynamis-Beaucedine", "Knii_Hoqo_the_Bisector" },
        { 84, 52, "Dynamis-Beaucedine", "Koo_Saxu_the_Everfast" },
        { 84, 53, "Dynamis-Beaucedine", "Kuu_Xuka_the_Nimble" },
        { 84, 54, "Dynamis-Beaucedine", "Maa_Zaua_the_Wyrmkeeper" },
        { 84, 55, "Dynamis-Beaucedine", "Nee_Huxa_the_Judgmental" },
        { 84, 56, "Dynamis-Beaucedine", "Puu_Timu_the_Phantasmal" },
        { 84, 57, "Dynamis-Beaucedine", "Ryy_Qihi_the_Idolrobber" },
        { 84, 58, "Dynamis-Beaucedine", "Soo_Jopo_the_Fiendking" },
        { 84, 59, "Dynamis-Beaucedine", "Xaa_Chau_the_Roctalon" },
        { 84, 60, "Dynamis-Beaucedine", "Xhoo_Fuza_the_Sublime" },
        { 85, 1, "Dynamis-Xarcabard", "Count_Zaebos" },
        { 85, 2, "Dynamis-Xarcabard", "Duke_Berith" },
        { 85, 3, "Dynamis-Xarcabard", "Marquis_Decarabia" },
        { 85, 4, "Dynamis-Xarcabard", "Duke_Gomory" },
        { 85, 5, "Dynamis-Xarcabard", "Marquis_Andras" },
        { 85, 6, "Dynamis-Xarcabard", "Prince_Seere" },
        { 85, 7, "Dynamis-Xarcabard", "Duke_Scox" },
        { 85, 8, "Dynamis-Xarcabard", "Marquis_Gamygyn" },
        { 85, 9, "Dynamis-Xarcabard", "Marquis_Orias" },
        { 85, 10, "Dynamis-Xarcabard", "Count_Raum" },
        { 85, 11, "Dynamis-Xarcabard", "Marquis_Nebiros" },
        { 85, 12, "Dynamis-Xarcabard", "Marquis_Sabnak" },
        { 85, 13, "Dynamis-Xarcabard", "Count_Vine" },
        { 85, 14, "Dynamis-Xarcabard", "King_Zagan" },
        { 85, 15, "Dynamis-Xarcabard", "Marquis_Cimeries" },
        { 85, 16, "Dynamis-Xarcabard", "Duke_Haures" },
        { 85, 17, "Dynamis-Xarcabard", "Marquis_Caim" },
        { 85, 18, "Dynamis-Xarcabard", "Baron_Avnas" },
        { 85, 19, "Dynamis-Xarcabard", "Count_Haagenti" },
        { 86, 1, "RuAun_Gardens", "Byakko" },
        { 86, 2, "RuAun_Gardens", "Despot" },
        { 86, 3, "RuAun_Gardens", "Genbu" },
        { 86, 4, "RuAun_Gardens", "Seiryu" },
        { 86, 5, "RuAun_Gardens", "Suzaku" },
        { 87, 1, "VeLugannon_Palace", "Brigandish_Blade" },
        { 87, 2, "VeLugannon_Palace", "Steam_Cleaner" },
        { 87, 3, "VeLugannon_Palace", "Zipacna" },
        { 88, 1, "The_Shrine_of_RuAvitau", "Faust" },
        { 88, 2, "The_Shrine_of_RuAvitau", "Kirin" },
        { 88, 3, "The_Shrine_of_RuAvitau", "Mother_Globe" },
        { 88, 4, "The_Shrine_of_RuAvitau", "Olla_Grande" },
        { 88, 5, "The_Shrine_of_RuAvitau", "Ullikummi" },
        { 89, 1, "AlTaieu", "Omyovra" },
        { 89, 2, "AlTaieu", "Ulyovra" },
        { 89, 3, "AlTaieu", "Jailer_of_Hope" },
        { 89, 4, "AlTaieu", "Jailer_of_Justice" },
        { 89, 5, "AlTaieu", "Jailer_of_Prudence" },
        { 90, 1, "Grand_Palace_of_HuXzoi", "Ixaern_MNK" },
        { 90, 2, "Grand_Palace_of_HuXzoi", "Jailer_of_Temperance" },
        { 91, 1, "The_Garden_of_RuHmet", "Ixaern_DRK" },
        { 91, 2, "The_Garden_of_RuHmet", "Ixaern_DRG" },
        { 91, 3, "The_Garden_of_RuHmet", "Jailer_of_Faith" },
        { 91, 4, "The_Garden_of_RuHmet", "Jailer_of_Fortitude" },
        { 92, 1, "Lufaise_Meadows", "Amaltheia" },
        { 92, 2, "Lufaise_Meadows", "Colorful_Leshy" },
        { 92, 3, "Lufaise_Meadows", "Defoliate_Leshy" },
        { 92, 4, "Lufaise_Meadows", "Kurrea" },
        { 92, 5, "Lufaise_Meadows", "Megalobugard" },
        { 92, 6, "Lufaise_Meadows", "Padfoot" },
        { 92, 7, "Lufaise_Meadows", "Flockbock" },
        { 92, 8, "Lufaise_Meadows", "Sengann" },
        { 92, 9, "Lufaise_Meadows", "Yal-un_Eke" },
        { 93, 1, "Misareaux_Coast", "Goaftrap" },
        { 93, 2, "Misareaux_Coast", "Gration" },
        { 93, 3, "Misareaux_Coast", "Odqan" },
        { 93, 4, "Misareaux_Coast", "Okyupete" },
        { 93, 5, "Misareaux_Coast", "Upyri" },
        { 93, 6, "Misareaux_Coast", "Ziphius" },
        { 94, 1, "Phomiuna_Aqueducts", "Tres_Duendes" },
        { 94, 2, "Phomiuna_Aqueducts", "Eba" },
        { 94, 3, "Phomiuna_Aqueducts", "Mahisha" },
        { 95, 1, "Sacrarium", "Elel" },
        { 96, 1, "Riverne_Site-A01", "Aiatar" },
        { 96, 2, "Riverne_Site-A01", "Heliodromos" },
        { 96, 3, "Riverne_Site-A01", "Shieldtrap" },
        { 97, 1, "Riverne_Site-B01", "Boroka" },
        { 97, 2, "Riverne_Site-B01", "Imdugud" },
        { 97, 3, "Riverne_Site-B01", "Unstable_Cluster" }
    }

    for _, entry in pairs(dailyNMs) do
        local zoneNum  = entry[1]
        local nmNum    = entry[2]
        local zoneName = entry[3]
        local mobName  = entry[4]

        --print(string.format("xi.zones.%s.mobs.%s.onMobDeath", zoneName, mobName))

        m:addOverride(string.format("xi.zones.%s.mobs.%s.onMobDeath", zoneName, mobName), function(mob, player, optParams)
            super(mob, player, optParams)
            
            local dailyQuestActive = player:getCharVar("[DailyQuest]Saltlik")
            local dailyZone        = player:getCharVar("[DailyQuest]Saltlik_zone")
            local dailyNM          = player:getCharVar("[DailyQuest]Saltlik_NM")

            if
                dailyQuestActive == 1 and
                dailyZone == zoneNum and
                dailyNM == nmNum
            then
                if optParams.isKiller then
                    player:setCharVar("[DailyQuest]Saltlik",2)
                    player:PrintToPlayer(string.format("You've killed %s, please return to Saltlik to claim your reward!",mob:getName()), 17)
                end
            end
        end)
    end
end)

return m
